version: '3'
services:
   db:
      image: mongo:4.2
      ports:
         - "27017:27017"
      volumes:
         - ./mongo-volume:/data/db
   web:
      build: 
         dockerfile: Dockerfile
         context: .
      depends_on:
         - db
      ports:
         - "8000:8000"
      volumes:
         - .:/code
      command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
